### ISSUE TITLE
[F.Rq.] Indicate hyperlinks that leave the site (on wiki pages)

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/tasvideos#1550]
The CSS class already exists, it just needs an icon.
```css
.extlink {
	background: url(/*haven't checked license on this*/"https://en.wikipedia.org/w/skins/Vector/resources/common/images/link-external-small-ltr-progressive.svg?30a3a") center right / 0.8em no-repeat;
	padding-right: 1em;
}
```
results in:
![screencap](https://user-images.githubusercontent.com/13409956/233244053-198cbe63-582e-49eb-ae4d-b1b527058d03.png)

Additional suggestion:
```css
.extlink[href^="https://en.wikipedia.org"], .extlink[href^="http://en.wikipedia.org"] {
	/* nominative use of Wikimedia Foundation trademark; artwork available under CC BY-SA 3.0 courtesy of User:Nohat on WP and Philip Metschan */
	background: url("https://upload.wikimedia.org/wikipedia/commons/5/55/Wikipedia_affiliative_mark.png") right -0.2em bottom 0.1em / 1.5em no-repeat;
	padding-right: 1.25em;
}
```
results in:
![screencap](https://user-images.githubusercontent.com/13409956/233251671-2f1a3069-fad0-43cb-91f3-23f25c96b928.png)
